name = "PosixChannels"
uuid = "0f0bcd13-3e12-4a59-be10-81f16103b667"
authors = ["Hugo Levy-Falk <hugo@klafyvel.me> and contributors"]
version = "0.1.0"

[deps]

[compat]
Aqua = "^0.8"
Test = "1"
JET = "^0.8"
julia = "^1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "JET"]
