name = "PosixChannels"
uuid = "0f0bcd13-3e12-4a59-be10-81f16103b667"
authors = ["Hugo Levy-Falk <hugo@klafyvel.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
